preserve_hierarchy: true
commit_message: '[ci skip]'

files:
  - source: /locales/en-US/*.json
    dest: /%original_file_name%
    translation: /locales/%locale%/%original_file_name%
    skip_untranslated_strings: true

project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
