<template>
  <div>
    <ModalTransfer
      v-if="enrolled"
      ref="modal_transfer"
      :wallet="wallet"
      :balance="auth.user.payout_data.balance"
      :base-fee="baseFee"
      :region="region"
    />
    <section class="universal-card">
      <h2>Withdraw</h2>
      <div v-if="auth.user.payout_data.balance > baseFee">
        <p>
          You have
          <strong>{{ $formatMoney(auth.user.payout_data.balance) }}</strong>
          available to withdraw.
          <span v-if="!enrolled"
            >Enroll in the Creator Monetization Program to withdraw your revenue.</span
          >
        </p>
      </div>
      <p v-else-if="auth.user.payout_data.balance > 0">
        You have made
        <strong>{{ $formatMoney(auth.user.payout_data.balance) }}</strong
        >, however you have not yet met the minimum of ${{ minWithdraw }} to withdraw.
      </p>
      <p v-else>
        You have not made anything on the Creator Monetization Program. Create some projects to
        start earning revenue!
      </p>
      <div v-if="!enrolled">
        <NuxtLink class="iconified-button" to="/settings/monetization">
          <SettingsIcon /> Set up Creator Monetization Program account
        </NuxtLink>
      </div>
      <div v-if="enrolled" class="input-group">
        <button
          v-if="auth.user.payout_data.balance >= baseFee"
          class="iconified-button brand-button"
          @click="$refs.modal_transfer.show()"
        >
          <TransferIcon /> Transfer to account
        </button>
        <NuxtLink class="iconified-button" to="/dashboard/revenue/transfers">
          <HistoryIcon /> View transfer history
        </NuxtLink>
        <NuxtLink class="iconified-button" to="/settings/monetization">
          <SettingsIcon /> Monetization settings
        </NuxtLink>
      </div>
    </section>
    <section class="universal-card">
      <h2>About the program</h2>
      <p>
        By uploading projects to Modrinth and withdrawing money from your account, you agree to the
        <nuxt-link to="/legal/cmp" class="text-link">Rewards Program Terms</nuxt-link>. For more
        information on how the rewards system works, see our information page
        <nuxt-link to="/legal/cmp-info" class="text-link">here</nuxt-link>.
      </p>
      <h2>Processing fees</h2>
      <p>
        Modrinth does not collect any money in processing fees. These fees are all passed along to
        you from our payment providers (Trolley, PayPal, and Venmo). To avoid paying unnecessary fee
        deductions, you may want to wait to transfer your money out after it accumulates for a bit.
      </p>
      <div class="markdown-body">
        <table>
          <tr>
            <th>Payment Method</th>
            <th>Transaction Fee</th>
            <th>Supported Countries</th>
          </tr>
          <tr>
            <td>ACH</td>
            <td>$1.00</td>
            <td>United States of America</td>
          </tr>
          <tr>
            <td>EFT</td>
            <td>$1.00</td>
            <td>Canada</td>
          </tr>
          <tr>
            <td>FPS</td>
            <td>$4.00</td>
            <td>United Kingdom</td>
          </tr>
          <tr>
            <td>NPP</td>
            <td>$4.00</td>
            <td>Australia</td>
          </tr>
          <tr>
            <td>BECS</td>
            <td>$4.00</td>
            <td>New Zealand</td>
          </tr>
          <tr>
            <td>FPSHK</td>
            <td>$4.00</td>
            <td>Hong Kong</td>
          </tr>
          <tr>
            <td>SEPA</td>
            <td>$4.00</td>
            <td>
              Europe (<a href="https://docs.trolley.com/api/#list-of-statuses">see countries</a>)
            </td>
          </tr>
          <tr>
            <td>IACH</td>
            <td>$4.00</td>
            <td>
              Europe (<a href="https://docs.trolley.com/api/#list-of-statuses">see countries</a>)
            </td>
          </tr>
          <tr>
            <td>Swift Wire</td>
            <td>$10.00</td>
            <td>
              Europe (<a href="https://docs.trolley.com/api/#list-of-statuses">see countries</a>)
            </td>
          </tr>
          <tr>
            <td>PayPal (US)</td>
            <td>$0.25 + 2% (max $1)</td>
            <td>United States of America</td>
          </tr>
          <tr>
            <td>PayPal (Global)</td>
            <td>2% (max $20)</td>
            <td>
              <a href="https://www.paypal.com/us/webapps/mpp/country-worldwide">see countries</a>
            </td>
          </tr>
          <tr>
            <td>Venmo</td>
            <td>$1.75</td>
            <td>United States of America</td>
          </tr>
        </table>
      </div>
      <br />
      <h2>Currency conversions</h2>
      <p>
        All revenue generated by Modrinth is in United States dollars. Any conversions to your local
        currency will happen at withdrawal and is not handled by Modrinth. Modrinth cannot guarantee
        any exchange rate, so only USD is displayed in the creator dashboard.
      </p>
      <p>For transactions, the following foreign exchange rates are provided:</p>
      <ul>
        <li>2.00% (Currency Group A)</li>
        <li>2.95% (Currency Group B)</li>
      </ul>
    </section>
  </div>
</template>
<script setup>
import TransferIcon from '~/assets/images/utils/transfer.svg'
import SettingsIcon from '~/assets/images/utils/settings.svg'
import HistoryIcon from '~/assets/images/utils/history.svg'
import ModalTransfer from '~/components/ui/ModalTransfer.vue'

useHead({
  title: 'Revenue - Modrinth',
})

const auth = await useAuth()

const baseFee = ref(0.0)
const wallet = ref(null)
const region = ref(null)
const enrolled = computed(
  () =>
    auth.value.user.payout_data.trolley_status === 'active' &&
    auth.value.user.payout_data.trolley_id
)

if (enrolled.value) {
  const { data: fees } = await useAsyncData(
    `user/${auth.value.user.id}/payouts_fees?amount=0.0`,
    () => useBaseFetch(`user/${auth.value.user.id}/payouts_fees?amount=0.0`)
  )
  baseFee.value = Number(fees.value.estimated_fees)
  wallet.value = fees.value.payout_method
  region.value = fees.value.country
}
</script>
<style lang="scss" scoped>
strong {
  color: var(--color-text-dark);
  font-weight: 500;
}
</style>
