<template>
  <div>
    <ModalTransfer
      v-if="enrolled"
      ref="modal_transfer"
      :wallet="$auth.user.payout_data.payout_wallet"
      :account-type="$auth.user.payout_data.payout_wallet_type"
      :account="$auth.user.payout_data.payout_address"
      :balance="$auth.user.payout_data.balance"
      :min-withdraw="minWithdraw"
    />
    <section class="universal-card">
      <h2>Withdraw</h2>
      <div v-if="$auth.user.payout_data.balance >= minWithdraw">
        <p>
          You have
          <span class="balance">${{ $auth.user.payout_data.balance }}</span>
          available to withdraw.
          <span v-if="!enrolled"
            >Enroll in the Creator Monetization Program to withdraw your
            revenue.</span
          >
        </p>

        <div v-if="enrolled" class="buttons">
          <button
            class="iconified-button brand-button"
            @click="$refs.modal_transfer.show()"
          >
            <TransferIcon /> Transfer to
            {{ $formatWallet($auth.user.payout_data.payout_wallet) }}
          </button>
          <NuxtLink class="iconified-button" to="/settings/monetization">
            <SettingsIcon /> Monetization settings
          </NuxtLink>
        </div>
      </div>
      <p v-else>
        You have made
        <span class="balance">${{ $auth.user.payout_data.balance }}</span
        >, however you have not yet met the minimum of ${{ minWithdraw }} to
        withdraw.
      </p>
      <div v-if="!enrolled">
        <NuxtLink class="iconified-button" to="/settings/monetization">
          <SettingsIcon /> Enroll in the Creator Monetization Program
        </NuxtLink>
      </div>
    </section>
    <section class="universal-card">
      <h2>Processing fees</h2>
      <p>
        To avoid paying unnecessary fee deductions, you may want to wait to
        transfer your money out after it accumulates for a bit rather than
        transferring as soon as you reach the minimum of ${{ minWithdraw }}.
      </p>
      <h3>PayPal</h3>
      <p>
        For transactions within the United States, PayPal charges a flat $0.25
        processing fee per transaction, and for international transactions,
        PayPal charges a 2% (up to $20) processing fee for each transaction.
      </p>
      <p>
        Since Modrinth cannot determine if you are international or not before
        initiating a transfer, each transaction made by any user will have 2%
        (up to $20) deducted from it in order to account for international
        PayPal processing fees. If the deduction from your Modrinth balance is
        more than the fee PayPal charges, the difference will be returned to
        your Modrinth balance.
      </p>
      <h3>Venmo (United States only)</h3>
      <p>
        Venmo will charge a $0.25 processing fee per transaction, which will be
        deducted from the amount you choose to transfer.
      </p>
      <h2>Currency conversions</h2>
      <p>
        All revenue generated by Modrinth is in United States dollars. Any
        conversions to your local currency will happen at withdraw and is not
        handled by Modrinth. Modrinth cannot guarantee any exchange rate, so
        only USD is displayed in the creator dashboard.
      </p>
    </section>
  </div>
</template>

<script>
import TransferIcon from '~/assets/images/utils/transfer.svg?inline'
import SettingsIcon from '~/assets/images/utils/settings.svg?inline'
import ModalTransfer from '~/components/ui/ModalTransfer'

export default {
  components: { TransferIcon, SettingsIcon, ModalTransfer },
  data() {
    return {
      minWithdraw: 0.26,
      enrolled:
        this.$auth.user.payout_data.payout_wallet &&
        this.$auth.user.payout_data.payout_wallet_type &&
        this.$auth.user.payout_data.payout_address,
    }
  },
  head: {
    title: 'Revenue - Modrinth',
  },
  methods: {},
}
</script>
<style lang="scss" scoped>
.balance {
  color: var(--color-text-dark);
  font-weight: bold;
}

.buttons {
  display: flex;
  flex-direction: row;
  gap: var(--spacing-card-sm);
}
</style>
