<template>
  <div>
    <ModalTransfer
      v-if="enrolled"
      ref="modal_transfer"
      :wallet="$auth.user.payout_data.payout_wallet"
      :account-type="$auth.user.payout_data.payout_wallet_type"
      :account="$auth.user.payout_data.payout_address"
      :balance="$auth.user.payout_data.balance"
      :min-withdraw="minWithdraw"
    />
    <section class="card">
      <h2>Withdraw</h2>
      <div v-if="$auth.user.payout_data.balance >= minWithdraw">
        <p>
          You have
          <span class="balance">${{ $auth.user.payout_data.balance }}</span>
          available to withdraw.
          <span v-if="!enrolled"
            >Enroll in the Creator Monetization Program to withdraw your
            revenue.</span
          >
        </p>

        <div v-if="enrolled" class="buttons">
          <button
            class="iconified-button brand-button"
            @click="$refs.modal_transfer.show()"
          >
            <TransferIcon /> Transfer to
            {{ $formatWallet($auth.user.payout_data.payout_wallet) }}
          </button>
          <NuxtLink class="iconified-button" to="/settings/monetization">
            <SettingsIcon /> Monetization settings
          </NuxtLink>
        </div>
      </div>
      <p v-else>
        You have made
        <span class="balance">${{ $auth.user.payout_data.balance }}</span
        >, however you have not yet met the minimum of ${{ minWithdraw }} to
        withdraw.
      </p>
      <div v-if="!enrolled">
        <NuxtLink class="iconified-button" to="/settings/monetization">
          <SettingsIcon /> Enroll in the Creator Monetization Program
        </NuxtLink>
      </div>
    </section>
    <section class="card">
      <h2>Processing fees</h2>
      <p>
        PayPal (and by extension, Venmo) charge a $0.25 processing fee for each
        transaction and this fee will come out of the money being transferred to
        you. To avoid paying unnecessary fees, you may want to transfer your
        money out after it accumulates a bit rather than transferring as soon as
        you reach the minimum of ${{ minWithdraw }}.
      </p>
      <h2>Currency conversions</h2>
      <p>
        All revenue generated by Modrinth is in United States dollars. Any
        conversions to your local currency will happen at withdraw and is not
        handled by Modrinth. Modrinth cannot guarantee any exchange rate, so
        only USD is displayed in the creator dashboard.
      </p>
    </section>
  </div>
</template>

<script>
import TransferIcon from '~/assets/images/utils/transfer.svg?inline'
import SettingsIcon from '~/assets/images/utils/settings.svg?inline'
import ModalTransfer from '~/components/ui/ModalTransfer'

export default {
  components: { TransferIcon, SettingsIcon, ModalTransfer },
  data() {
    return {
      minWithdraw: 0.25,
      enrolled:
        this.$auth.user.payout_data.payout_wallet &&
        this.$auth.user.payout_data.payout_wallet_type &&
        this.$auth.user.payout_data.payout_address,
    }
  },
  head: {
    title: 'Revenue - Modrinth',
  },
  methods: {},
}
</script>
<style lang="scss" scoped>
.card {
  padding: var(--spacing-card-lg);

  > :last-child {
    margin-bottom: 0;
  }

  .iconified-button {
    width: fit-content;
  }
}

.balance {
  color: var(--color-text-dark);
  font-weight: bold;
}

.buttons {
  display: flex;
  flex-direction: row;
  gap: var(--spacing-card-sm);
}
</style>
