<template>
  <div>
    <ModalTransfer
      ref="modal_transfer"
      :wallet="wallet"
      :account-type="accountType"
      :account="account"
      :balance="currentBalance"
      :min-withdraw="minWithdraw"
    />
    <section class="card">
      <h2>Withdraw</h2>
      <div v-if="currentBalance >= minWithdraw">
        <p>
          You have
          <span class="balance">${{ currentBalance }}</span> available to
          withdraw.
          <span v-if="!enrolled"
            >Enroll in the Creator Monetization Program to withdraw your
            revenue.</span
          >
        </p>

        <div v-if="enrolled" class="buttons">
          <button
            class="iconified-button brand-button"
            @click="$refs.modal_transfer.show()"
          >
            <TransferIcon /> Transfer to {{ $formatWallet(wallet) }}
          </button>
          <NuxtLink class="iconified-button" to="/settings/monetization">
            <SettingsIcon /> Manage enrollment
          </NuxtLink>
        </div>
      </div>
      <p v-else>
        You have made
        <span class="balance">${{ currentBalance }}</span
        >, however you have not yet met the minimum of ${{ minWithdraw }} to
        withdraw.
      </p>
      <div v-if="!enrolled">
        <NuxtLink class="iconified-button" to="/settings/monetization">
          <SettingsIcon /> Enroll in the Creator Monetization Program
        </NuxtLink>
      </div>
    </section>
    <section class="card">
      <h2>Currency conversions</h2>
      <p>
        All revenue generated by Modrinth is in United States dollars. Any
        conversions to your local currency will happen at withdraw and is not
        handled by Modrinth. Modrinth cannot guarantee any exchange rate, so
        only USD is displayed in the creator dashboard.
      </p>
    </section>
  </div>
</template>

<script>
import TransferIcon from '~/assets/images/utils/transfer.svg?inline'
import SettingsIcon from '~/assets/images/utils/settings.svg?inline'
import ModalTransfer from '~/components/ui/ModalTransfer'

export default {
  components: { TransferIcon, SettingsIcon, ModalTransfer },
  data() {
    return {
      currentBalance: 61,
      minWithdraw: 5,
      wallet: 'paypal',
      accountType: 'email',
      account: 'example@gmail.com',
      enrolled: true,
    }
  },
  fetch() {},
  head: {
    title: 'Revenue - Modrinth',
  },
  methods: {},
}
</script>
<style lang="scss" scoped>
.card {
  padding: var(--spacing-card-lg);

  > :last-child {
    margin-bottom: 0;
  }

  .iconified-button {
    width: fit-content;
  }
}

.balance {
  color: var(--color-text-dark);
  font-weight: bold;
}

.buttons {
  display: flex;
  flex-direction: row;
  gap: var(--spacing-card-sm);
}
</style>
