name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Cloudflare Pages deployment
        uses: WalshyDev/cf-pages-await@v1
        with:
          # TODO: Set up CF API Token on the GitHub org level to use instead of email & api key
          apiToken: ${{ secrets.CF_API_TOKEN }}

          # accountEmail: ${{ secrets.CF_ACCOUNT_EMAIL  }}
          # apiKey: ${{ secrets.CF_API_KEY  }}

          accountId: "9ddae624c98677d68d93df6e524a6061"
          project: "knossos"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          commitHash: ${{ steps.push-changes.outputs.commit-hash }}
