name: Crowdin (cleanup)

on: [delete]

concurrency:
  group: i18n-management

env:
  CROWDIN_CLI_VERSION: '3.18.0'

jobs:
  preflight_check:
    name: 'Pre-flight check'
    runs-on: ubuntu-22.04
    concurrency:
      group: i18n-cleanup:${{ github.event.ref }}
      cancel-in-progress: true
    if: github.event.ref_type == 'branch' && !startsWith(github.event.ref, 'ref/heads/crowdin-pull/')
    steps:
      - name: Preflight check
        id: check
        shell: bash
        run: |
          PREFLIGHT_CHECK_RESULT=true

          function flight_failure () {
            if [ "$PREFLIGHT_CHECK_RESULT" = true ]; then
              echo "One or more pre-flight checks failed!"
              echo ""
              PREFLIGHT_CHECK_RESULT=false
            fi
            echo "- $1"
          }

          if [ "$CROWDIN_PROJECT_ID_DEFINED" != true ]; then
            flight_failure "CROWDIN_PROJECT_ID variable is not defined (required to push)"
          fi

          if [ "$CROWDIN_PERSONAL_TOKEN_DEFINED" != true ]; then
            flight_failure "CROWDIN_PERSONAL_TOKEN secret is not defined (required to push)"
          fi

          echo "flight_ok=$PREFLIGHT_CHECK_RESULT" >> "$GITHUB_OUTPUT"
        env:
          CROWDIN_PROJECT_ID_DEFINED: ${{ vars.CROWDIN_PROJECT_ID != '' }}
          CROWDIN_PERSONAL_TOKEN_DEFINED: ${{ secrets.CROWDIN_PERSONAL_TOKEN != '' }}
    outputs:
      ready: ${{ steps.check.outputs.flight_ok == 'true' }}
  delete_crowdin_branch:
    name: 'Delete Crowdin branch'
    runs-on: ubuntu-22.04
    needs: preflight_check
    if: needs.preflight_check.outputs.ready == 'true'
    concurrency:
      group: i18n-cleanup:${{ github.event.ref }}
      cancel-in-progress: true
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get branch name from ref
        id: branch-name
        shell: bash
        run: echo "safe_branch_name=$(echo "${{ github.event.ref }}" | sed -e "s/[\\\\/\\:*?\"<>|]/_/g")" >> "$GITHUB_OUTPUT"

      # Crowdin GitHub Action is currently broken and doesn't properly run commands that contain spaces
      # See https://github.com/crowdin/github-action/issues/192
      - name: Download Crowdin CLI
        uses: robinraju/release-downloader@v1.9
        with:
          repository: crowdin/crowdin-cli
          tag: ${{ env.CROWDIN_CLI_VERSION }}
          fileName: 'crowdin-cli.zip'
          out-file-path: '.crowdin'

      - name: Delete translations branch on Crowdin
        shell: bash
        run: |
          CROWDIN_DIR="$PWD/.crowdin"
          unzip "$CROWDIN_DIR/crowdin-cli.zip" -d "$CROWDIN_DIR"
          CROWDIN_CLI_JAR="$CROWDIN_DIR/${{ env.CROWDIN_CLI_VERSION }}/crowdin-cli.jar"
          java -jar "$CROWDIN_CLI_JAR" branch delete "[${{ github.repository_owner }}.${{ github.event.repository.name }}] ${{ steps.branch-name.outputs.safe_branch_name }}"
        continue-on-error: true
        env:
          CROWDIN_PROJECT_ID: ${{ vars.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      # - name: Delete translations branch on Crowdin
      #   uses: crowdin/github-action@v1
      #   with:
      #     command: 'branch'
      #     command_args: 'delete "[${{ github.repository_owner }}.${{ github.event.repository.name }}] ${{ steps.branch-name.outputs.safe_branch_name }}"'
      #   env:
      #     CROWDIN_PROJECT_ID: ${{ vars.CROWDIN_PROJECT_ID }}
      #     CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
      #   continue-on-error: true

      - name: Delete Git branch
        shell: bash
        run: 'git push origin :crowdin-pull/${{ github.event.ref }}'
        continue-on-error: true
